"""
data.py
-------
Loads and prepares all data for the ML vs Factor Models project.

REAL DATA (when available):
    - Factors: Download CSVs from https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html
        * F-F_Research_Data_5_Factors_2x3.CSV  -> data/raw/
        * F-F_Momentum_Factor.CSV               -> data/raw/
        * F-F_ST_Reversal_Factor.CSV            -> data/raw/
    - Returns: Any monthly equity return panel (e.g. CRSP, Compustat, or yfinance bulk download)
        * Format: CSV with Date index, one column per ticker, values = simple monthly returns

SYNTHETIC DATA (default, for development):
    - Statistically calibrated to match real FF5 factor properties
    - Factor structure preserved: assets have realistic beta exposures
    - Swap real data in via load_real_data() below — zero code changes needed elsewhere
"""

import numpy as np
import pandas as pd
from pathlib import Path

RAW = Path("data/raw")
PROCESSED = Path("data/processed")

# ── Synthetic data generation ───────────────────────────────────────────────

def generate_synthetic_data(
    start: str = "2000-01",
    end: str = "2024-12",
    n_assets: int = 50,
    seed: int = 42,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Generate a synthetic factor + returns dataset.

    Statistical calibration targets (monthly):
        Mkt-RF:  mean=0.6%,  vol=4.5%   (CRSP 2000-2024)
        SMB:     mean=0.2%,  vol=3.1%
        HML:     mean=0.3%,  vol=3.1%
        RMW:     mean=0.3%,  vol=2.2%
        CMA:     mean=0.3%,  vol=2.0%
        Mom:     mean=0.7%,  vol=4.2%
        ST_Rev:  mean=0.4%,  vol=3.5%

    Returns
    -------
    factors : DataFrame, shape (T, 8)  — factor returns + RF
    returns : DataFrame, shape (T, n_assets) — gross asset returns
    """
    rng = np.random.default_rng(seed)
    dates = pd.date_range(start, end, freq="ME")
    T = len(dates)

    # ── Factor returns ──────────────────────────────────────────────────────
    # Correlated factor innovations (rough empirical correlation structure)
    corr = np.array([
        # Mkt   SMB   HML   RMW   CMA   Mom   STR
        [ 1.00,  0.25, -0.25, -0.15, -0.35, -0.15,  0.00],
        [ 0.25,  1.00, -0.10, -0.35, -0.20, -0.05,  0.05],
        [-0.25, -0.10,  1.00,  0.10,  0.65, -0.15,  0.10],
        [-0.15, -0.35,  0.10,  1.00,  0.10,  0.10, -0.05],
        [-0.35, -0.20,  0.65,  0.10,  1.00, -0.10,  0.05],
        [-0.15, -0.05, -0.15,  0.10, -0.10,  1.00, -0.55],
        [ 0.00,  0.05,  0.10, -0.05,  0.05, -0.55,  1.00],
    ])
    vols = np.array([0.045, 0.031, 0.031, 0.022, 0.020, 0.042, 0.035])
    means = np.array([0.006, 0.002, 0.003, 0.003, 0.003, 0.007, 0.004])

    cov = np.diag(vols) @ corr @ np.diag(vols)
    raw_factors = rng.multivariate_normal(means, cov, size=T)

    # GARCH-like volatility clustering on market and momentum
    for col_idx in [0, 5]:
        vol_t = np.ones(T) * vols[col_idx]
        for t in range(1, T):
            vol_t[t] = 0.92 * vol_t[t-1] + 0.08 * abs(raw_factors[t-1, col_idx])
        raw_factors[:, col_idx] *= vol_t / vol_t.mean()

    rf = np.clip(rng.normal(0.002, 0.001, T), 0, None)

    factors = pd.DataFrame(
        raw_factors,
        index=dates,
        columns=["Mkt_RF", "SMB", "HML", "RMW", "CMA", "Mom", "ST_Rev"],
    )
    factors["RF"] = rf
    factors.index.name = "Date"

    # ── Asset returns ───────────────────────────────────────────────────────
    # Each asset: R_i = alpha_i + sum(beta_ij * F_j) + epsilon_i
    rng2 = np.random.default_rng(seed + 1)

    # Random factor loadings (cross-sectional dispersion calibrated to real data)
    loadings = {
        "Mkt_RF": rng2.uniform(0.5, 1.5, n_assets),
        "SMB":    rng2.uniform(-1.0, 1.0, n_assets),
        "HML":    rng2.uniform(-0.5, 1.5, n_assets),
        "RMW":    rng2.uniform(-0.5, 1.0, n_assets),
        "CMA":    rng2.uniform(-0.5, 1.0, n_assets),
        "Mom":    rng2.uniform(-0.3, 0.8, n_assets),
    }

    # Small random alphas (most should be near zero)
    alphas = rng2.normal(0, 0.001, n_assets)

    systematic = sum(
        np.outer(factors[f].values, loadings[f]) for f in loadings
    )  # shape (T, n_assets)

    idio_vol = rng2.uniform(0.03, 0.06, n_assets)  # 3-6% monthly idiosyncratic vol
    idio = rng2.normal(0, 1, (T, n_assets)) * idio_vol[np.newaxis, :]

    asset_names = [f"Asset_{i:02d}" for i in range(n_assets)]
    returns = pd.DataFrame(
        alphas[np.newaxis, :] + systematic + idio,
        index=dates,
        columns=asset_names,
    )
    returns.index.name = "Date"

    return factors, returns


# ── Real data loaders (swap in when available) ───────────────────────────────

def load_real_factors(raw_dir: Path = RAW) -> pd.DataFrame:
    """
    Load factors from data/raw/factors.csv (generated by fetch_data.py).
    Falls back to getFamaFrenchFactors if CSV not found.
    """
    factors_path = raw_dir / "factors.csv"

    if factors_path.exists():
        factors = pd.read_csv(factors_path, index_col=0, parse_dates=True)
        factors.index = pd.to_datetime(factors.index) + pd.offsets.MonthEnd(0)
        factors.index.name = "Date"
        return factors.astype(float)

    # Fallback: fetch directly
    print("  factors.csv not found — fetching via getFamaFrenchFactors...")
    import getFamaFrenchFactors as gff

    ff5 = gff.famaFrench5Factor(frequency="m")
    ff5 = ff5.rename(columns={"date_ff_factors": "Date", "Mkt-RF": "Mkt_RF"})
    ff5 = ff5.set_index("Date")

    mom = gff.momentumFactor(frequency="m")
    mom = mom.rename(columns={"date_ff_factors": "Date", "MOM": "Mom"})
    mom = mom.set_index("Date")

    factors = ff5.join(mom[["Mom"]], how="inner")
    factors["ST_Rev"] = 0.0
    factors.index = pd.to_datetime(factors.index) + pd.offsets.MonthEnd(0)
    factors.index.name = "Date"
    return factors.astype(float)


def load_real_returns(path: Path = RAW / "returns.csv") -> pd.DataFrame:
    """
    Load a pre-built monthly returns panel.
    Format: CSV, Date index (YYYY-MM-DD), columns = ticker symbols, values = simple returns.
    """
    df = pd.read_csv(path, index_col=0, parse_dates=True)
    df.index = df.index + pd.offsets.MonthEnd(0)
    df.index.name = "Date"
    return df.astype(float)


# ── Main entry point ─────────────────────────────────────────────────────────

def load_data(use_synthetic: bool = True) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Returns (factors, returns) aligned on the same monthly date index.

    Parameters
    ----------
    use_synthetic : bool
        True  → generate synthetic data (default, for development)
        False → load real data from data/raw/ (requires manual CSV download)
    """
    if use_synthetic:
        print("Using synthetic data (statistically calibrated to FF5 properties)")
        factors, returns = generate_synthetic_data()
    else:
        print("Loading real data from data/raw/")
        factors = load_real_factors()
        returns = load_real_returns()

    # Align on common dates
    common_dates = factors.index.intersection(returns.index)
    factors = factors.loc[common_dates]
    returns = returns.loc[common_dates]

    print(f"  Factors:  {factors.shape}  ({factors.index[0].date()} → {factors.index[-1].date()})")
    print(f"  Returns:  {returns.shape}")
    return factors, returns


# ── Quick smoke test ─────────────────────────────────────────────────────────
if __name__ == "__main__":
    factors, returns = load_data(use_synthetic=True)
    print("\nFactor summary:")
    print(factors.describe().round(4))
    print("\nReturn cross-section (mean across assets):")
    print(returns.describe().mean().round(4))